export const FETCH_FILMS_REQUESTED = 'FETCH_FILMS_REQUESTED';
export const FETCH_FILMS_SUCCESS = 'FETCH_FILMS_SUCCESS';
export const FETCH_FILMS_FAILURE = 'FETCH_FILMS_FAILURE';
export const SET_RADIO_SEARCH_ACTOR = 'SET_RADIO_SEARCH_ACTOR';
export const SET_RADIO_SEARCH_FILM = 'SET_RADIO_SEARCH_FILM';
